---
title: "Acompanhamento Covid 19"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#these libraries are necessary
library(readxl)
library(httr)
library(ggplot2)
library(dplyr)
library(tidyr)
# devtools::install_github("rensa/ggflags")
# library(ggflags)
options(scipen=999)
```

## Acompanhamento

Os dados são obtidos de [deste link](https://www.ecdc.europa.eu/sites/default/files/documents/COVID-19-geographic-disbtribution-worldwide-) e atualizado diariamente.

```{r,echo=FALSE,warning=FALSE,results='hide'}
# Please note that this script updates every day automatically using the time of your computer. Hence, it might show an error message if you try to download the file before we have updated it.

#create the URL where the dataset is stored with automatic updates every day

url <- paste("https://www.ecdc.europa.eu/sites/default/files/documents/COVID-19-geographic-disbtribution-worldwide-",format(Sys.time(), "%Y-%m-%d"), ".xlsx", sep = "")

#download the dataset from the website to a local temporary file

GET(url, authenticate(":", ":", type="ntlm"), write_disk(tf <- tempfile(fileext = ".xlsx")))

#read the Dataset sheet into “R”

data <- read_excel(tf)
```

## Dados Gerais

O gráfico abaixo apresenta as linhas de crescimento dos casos confirmados e mortes por Covid 19 até o momento no mundo:

```{r, echo=FALSE}
data %>% pivot_longer(cols=c(Cases,Deaths)) %>% ggplot(aes(x=DateRep, y=value)) +  
geom_bar(aes(fill=name), position = "dodge",stat='identity') +
  xlab("Data") + ylab("Casos confirmados/Mortes")+
  theme_minimal() +labs(title=paste("Casos confirmados e mortes no mundo - ", format(Sys.time(), "%d/%m/%Y")), caption = "Em escala logarítimica.Os dados são atualizados diariamente.\n  Fonte:https://www.ecdc.europa.eu/sites/default/files/documents/COVID-19-geographic-disbtribution-worldwide") + scale_fill_manual(name="", breaks = c("Cases","Deaths"),labels=c("Casos", "Mortes"), values = c("blue","red"))

```


Para fins de comparação com estimativas internacionais, o gráfico abaixo apresenta a curva de casos confirmados cumulativa a partir do dia 0:

```{r,echo=FALSE,warning=FALSE}
prepared_data <- data %>% 
  filter(Cases > 0 ) %>% 
  arrange(DateRep,GeoId) %>%
  group_by(GeoId) %>% 
  mutate(sum_cases = cumsum(Cases),
         sum_deaths = cumsum(Deaths),
         days_from_first = as.Date(DateRep, format= "%Y-%m-%d") - as.Date(min(DateRep), format= "%Y-%m-%d"))
         

long_data <- prepared_data %>% pivot_longer(cols=c(Cases,Deaths,sum_cases,sum_deaths))

list_of_countries <- data %>% select(GeoId, "Countries and territories") %>% distinct()
```


```{r,echo=FALSE,warning=FALSE}
# Plot
seq_dates = seq(0,100,1)
labels <- c( "EUA","Brasil","China", "França","Itália","Espanha","Coréia do Sul")
breaks <- c('US',"BR",'CN','FR','IT','ES','KR')
prepared_data %>% 
  filter(GeoId %in% c('BR','US','CN','FR','IT','ES','KR')) %>% 
  ggplot(aes(x=days_from_first, y=sum_cases, color=GeoId, linetype=GeoId)) + geom_line(size=1)+ 
  scale_y_log10() + xlim(0,80) + theme_minimal() + labs(title = paste("Evolução dos Casos Covid-19 - ",format(Sys.time(), "%d/%m/%Y")), caption = "Em escala logarítimica.Os dados são atualizados diariamente.\n Fonte:https://www.ecdc.europa.eu/sites/default/files/documents/COVID-19-geographic-disbtribution-worldwide") + xlab("Dias desde 1º caso") + ylab("Casos confirmados") +
  scale_color_manual(name="País",labels=labels, breaks=breaks,values=c("red","blue",'green','yellow','orange','grey',"pink"))+
  scale_linetype_manual(name="País",labels=labels, breaks=breaks, values=c(1,2,3,4,5,6,7))+
theme(legend.position="bottom") 
```